#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

CODEX_SESSIONS_DIR = Path.home() / '.codex' / 'sessions'

# Official Codex credit rates (credits per 1M tokens), from OpenAI Help Center
# https://help.openai.com/en/articles/20001106-codex-rate-card
CREDIT_RATES_PER_MTOK = {
    'gpt-5.5': {'input': 125.0, 'cached_input': 12.50, 'output': 750.0},
    'gpt-5.4': {'input': 62.50, 'cached_input': 6.250, 'output': 375.0},
    'gpt-5.4-mini': {'input': 18.75, 'cached_input': 1.875, 'output': 113.0},
    'gpt-5.3-codex': {'input': 43.75, 'cached_input': 4.375, 'output': 350.0},
    'gpt-5.2': {'input': 43.75, 'cached_input': 4.375, 'output': 350.0},
}

# Official API standard pricing ($ per 1M tokens), from OpenAI API pricing.
# https://openai.com/api/pricing/
USD_RATES_PER_MTOK = {
    'gpt-5.5': {'input': 5.00, 'cached_input': 0.50, 'output': 30.00},
    'gpt-5.4': {'input': 2.50, 'cached_input': 0.25, 'output': 15.00},
    'gpt-5.4-mini': {'input': 0.75, 'cached_input': 0.075, 'output': 4.50},
}

FIELD_DESCRIPTIONS = {
    'input_tokens': (
        'Input tokens reported by Codex for the usage block. '
        'They represent the prompt/context sent to the model for that block.'
    ),
    'cached_input_tokens': (
        'Input tokens reused from cache. They are reported separately to show '
        'how much of the input was cache-backed. In these Codex reports they usually '
        'behave as an informational subset of input, not an extra amount to add again to total_tokens.'
    ),
    'uncached_input_tokens': (
        'Derived field: input_tokens - cached_input_tokens. '
        'This approximates the portion of input that was not served from cache.'
    ),
    'output_tokens': (
        'Output tokens generated by the model for the reported usage block.'
    ),
    'reasoning_output_tokens': (
        'Informational output subfield reported by Codex for reasoning tokens. '
        'It is usually part of output_tokens, not an additional amount.'
    ),
    'visible_output_tokens': (
        'Derived field: output_tokens - reasoning_output_tokens. '
        'This approximates the non-reasoning / externally visible output portion.'
    ),
    'total_tokens': (
        'Total tokens reported by Codex for that block. In the observed examples it matches '
        'input_tokens + output_tokens; it does not add cached_input_tokens or reasoning_output_tokens again.'
    ),
    'model_context_window': (
        'Maximum model context window reported by Codex for this session.'
    ),
    'plan_type': (
        'Subscription plan recorded by Codex for the session (for example: plus, pro, business).'
    ),
}


@dataclass
class SessionData:
    session_file: Path
    session_meta: dict[str, Any] | None
    turn_context: dict[str, Any] | None
    last_token_event: dict[str, Any]


def normalize_model_name(model: str | None) -> str | None:
    if not model:
        return None
    key = model.strip().lower().replace(' ', '-').replace('_', '-')
    aliases = {
        'gpt-5.4-mini': 'gpt-5.4-mini',
        'gpt-5.4mini': 'gpt-5.4-mini',
        'gpt-5.5': 'gpt-5.5',
        'gpt-5.4': 'gpt-5.4',
        'gpt-5.3-codex': 'gpt-5.3-codex',
        'gpt-5.2': 'gpt-5.2',
    }
    return aliases.get(key, key)


def latest_session_file(base_dir: Path) -> Path:
    files = [p for p in base_dir.rglob('*.jsonl') if p.is_file()]
    if not files:
        raise FileNotFoundError(f'No Codex session JSONL found under {base_dir}')
    return max(files, key=lambda p: p.stat().st_mtime_ns)


def load_session(session_file: Path) -> SessionData:
    session_meta = None
    turn_context = None
    last_token_event = None

    with session_file.open('r', encoding='utf-8') as fh:
        for raw_line in fh:
            raw_line = raw_line.strip()
            if not raw_line:
                continue
            try:
                obj = json.loads(raw_line)
            except Exception:
                continue

            typ = obj.get('type')
            payload = obj.get('payload') or {}

            if typ == 'session_meta' and session_meta is None:
                session_meta = payload
            elif typ == 'turn_context':
                turn_context = payload
            elif typ == 'event_msg' and payload.get('type') == 'token_count':
                last_token_event = obj

    if not last_token_event:
        raise RuntimeError(f'No token_count event found in {session_file}')

    return SessionData(
        session_file=session_file,
        session_meta=session_meta,
        turn_context=turn_context,
        last_token_event=last_token_event,
    )


def calc_costs(model: str | None, usage: dict[str, Any]) -> dict[str, Any]:
    normalized = normalize_model_name(model)
    input_tokens = float(usage.get('input_tokens') or 0)
    cached_input_tokens = float(usage.get('cached_input_tokens') or 0)
    output_tokens = float(usage.get('output_tokens') or 0)

    result: dict[str, Any] = {
        'model_for_pricing': normalized,
        'credits_standard': None,
        'price_usd_api_standard': None,
        'credits_breakdown_standard': None,
        'price_usd_breakdown_api_standard': None,
        'pricing_notes': [],
    }

    if normalized in CREDIT_RATES_PER_MTOK:
        rates = CREDIT_RATES_PER_MTOK[normalized]
        input_component = input_tokens * rates['input'] / 1_000_000
        cached_input_component = cached_input_tokens * rates['cached_input'] / 1_000_000
        output_component = output_tokens * rates['output'] / 1_000_000
        result['credits_breakdown_standard'] = {
            'input_component': input_component,
            'cached_input_component': cached_input_component,
            'output_component': output_component,
        }
        result['credits_standard'] = input_component + cached_input_component + output_component
    else:
        result['pricing_notes'].append('No Codex credit rate is mapped for this model in the script.')

    if normalized in USD_RATES_PER_MTOK:
        rates = USD_RATES_PER_MTOK[normalized]
        input_component = input_tokens * rates['input'] / 1_000_000
        cached_input_component = cached_input_tokens * rates['cached_input'] / 1_000_000
        output_component = output_tokens * rates['output'] / 1_000_000
        result['price_usd_breakdown_api_standard'] = {
            'input_component': input_component,
            'cached_input_component': cached_input_component,
            'output_component': output_component,
        }
        result['price_usd_api_standard'] = input_component + cached_input_component + output_component
    else:
        result['pricing_notes'].append('No standard API USD price is mapped for this model in the script.')

    result['pricing_notes'].append(
        'Both credits_standard and price_usd_api_standard include cached_input_tokens as a separately billed component using the lower cached-input rate, not the standard input rate.'
    )
    result['pricing_notes'].append(
        'Credits are computed with the official token-based Codex rate card. '
        'If the task used Speed mode, this value may be understated because Speed has separate rates.'
    )
    result['pricing_notes'].append(
        'USD is shown as a standard API pricing reference, not as ChatGPT/Codex billing.'
    )
    return result


def fmt_num(value: Any, decimals: int = 6) -> str:
    if value is None:
        return 'n/a'
    if isinstance(value, int):
        return str(value)
    try:
        num = float(value)
    except Exception:
        return str(value)
    text = f'{num:.{decimals}f}'
    text = text.rstrip('0').rstrip('.')
    return text if text else '0'


def usage_with_breakdown(raw_usage: dict[str, Any]) -> dict[str, Any]:
    input_tokens = int(raw_usage.get('input_tokens') or 0)
    cached_input_tokens = int(raw_usage.get('cached_input_tokens') or 0)
    output_tokens = int(raw_usage.get('output_tokens') or 0)
    reasoning_output_tokens = int(raw_usage.get('reasoning_output_tokens') or 0)
    total_tokens = int(raw_usage.get('total_tokens') or 0)

    uncached_input_tokens = max(input_tokens - cached_input_tokens, 0)
    visible_output_tokens = max(output_tokens - reasoning_output_tokens, 0)

    values = {
        'input_tokens': input_tokens,
        'cached_input_tokens': cached_input_tokens,
        'uncached_input_tokens': uncached_input_tokens,
        'output_tokens': output_tokens,
        'reasoning_output_tokens': reasoning_output_tokens,
        'visible_output_tokens': visible_output_tokens,
        'total_tokens': total_tokens,
    }

    detailed = {}
    for key, value in values.items():
        entry = {
            'value': value,
            'description': FIELD_DESCRIPTIONS[key],
        }
        if key in {'uncached_input_tokens', 'visible_output_tokens'}:
            entry['derived_from_reported_usage'] = True
        detailed[key] = entry
    return detailed


def build_report(data: SessionData) -> dict[str, Any]:
    payload = data.last_token_event['payload']
    info = payload.get('info') or {}
    rate_limits = payload.get('rate_limits') or {}
    raw_usage_last = info.get('last_token_usage') or {}
    raw_usage_total = info.get('total_token_usage') or {}
    turn_context = data.turn_context or {}
    session_meta = data.session_meta or {}

    model = (
        turn_context.get('model')
        or session_meta.get('model')
        or session_meta.get('payload', {}).get('model')
    )

    session_meta_timestamp = (data.session_meta or {}).get('timestamp')
    session_event_timestamp = data.last_token_event.get('timestamp')

    return {
        'session_file': str(data.session_file),
        'source_fidelity': {
            'origin': 'Codex session JSONL generated by the real runtime',
            'event_type': 'event_msg',
            'event_payload_type': 'token_count',
            'why_faithful': (
                'These numbers come from Codex structured runtime logs for the real session, '
                'not from local estimation or approximate tokenization done by this script.'
            ),
            'limitation': (
                'The credit and USD calculations depend on the official rates mapped in this script and assume standard pricing; '
                'if Speed mode or another special pricing mode was used and is not visible in the JSONL, that will not be reflected here.'
            ),
        },
        'session': {
            'started_at': session_meta_timestamp,
            'started_at_description': 'Session start timestamp recorded in session_meta.timestamp within the Codex session JSONL.',
            'model': model,
            'model_description': 'Active model taken from turn_context/session JSONL when available; not estimated.',
            'plan_type': rate_limits.get('plan_type'),
            'plan_type_description': FIELD_DESCRIPTIONS['plan_type'],
            'model_context_window': info.get('model_context_window'),
            'model_context_window_description': FIELD_DESCRIPTIONS['model_context_window'],
        },
        'latest_execution': {
            'recorded_at': session_event_timestamp,
            'recorded_at_description': 'Timestamp of the latest token_count event used for this latest execution block.',
            'description': (
                'Latest usage block reported by Codex inside this session. '
                'It is the best faithful approximation of the latest billed/countable execution chunk recorded in the JSONL.'
            ),
            'usage': usage_with_breakdown(raw_usage_last),
            'costs': calc_costs(model, raw_usage_last),
        },
        'session_total': {
            'description': (
                'Total accumulated usage reported by Codex for the session up to the last token_count event found.'
            ),
            'usage': usage_with_breakdown(raw_usage_total),
            'costs': calc_costs(model, raw_usage_total),
        },
        'field_descriptions': FIELD_DESCRIPTIONS,
    }


def print_human(report: dict[str, Any]) -> None:
    session = report['session']
    latest = report['latest_execution']
    total = report['session_total']
    fidelity = report['source_fidelity']

    print('Codex usage report')
    print('==================')
    print(f"session_file: {report['session_file']}")
    print(f"session_started_at: {session.get('started_at')}")
    print(f"  description: {session.get('started_at_description')}")
    print(f"model: {session.get('model')}")
    print(f"  description: {session.get('model_description')}")
    print(f"plan_type: {session.get('plan_type')}")
    print(f"  description: {session.get('plan_type_description')}")
    print(f"model_context_window: {session.get('model_context_window')}")
    print(f"  description: {session.get('model_context_window_description')}")

    for title, block in [('latest_execution', latest), ('session_total', total)]:
        print(f'\n{title}')
        print('-' * len(title))
        if block.get('recorded_at') is not None:
            print(f"recorded_at: {block.get('recorded_at')}")
            print(f"  description: {block.get('recorded_at_description')}")
        print(f"description: {block['description']}")
        usage = block['usage']
        for key in (
            'input_tokens',
            'cached_input_tokens',
            'uncached_input_tokens',
            'output_tokens',
            'reasoning_output_tokens',
            'visible_output_tokens',
            'total_tokens',
        ):
            entry = usage[key]
            print(f"{key}: {entry['value']}")
            print(f"  description: {entry['description']}")
            if entry.get('derived_from_reported_usage'):
                print('  derived_from_reported_usage: true')

        costs = block['costs']
        print('costs:')
        print(f"  credits_standard: {fmt_num(costs.get('credits_standard'))}")
        print('    description: Codex credits computed from the official token-based Codex rate card using the detected model and standard rates.')
        if costs.get('credits_breakdown_standard'):
            cb = costs['credits_breakdown_standard']
            print('  credits_breakdown_standard:')
            print(f"    input_component: {fmt_num(cb.get('input_component'))}")
            print('      description: Credit cost contribution from input_tokens at the standard input credit rate.')
            print(f"    cached_input_component: {fmt_num(cb.get('cached_input_component'))}")
            print('      description: Credit cost contribution from cached_input_tokens at the lower cached-input credit rate.')
            print(f"    output_component: {fmt_num(cb.get('output_component'))}")
            print('      description: Credit cost contribution from output_tokens at the standard output credit rate.')
        print(f"  price_usd_api_standard: {fmt_num(costs.get('price_usd_api_standard'))}")
        print('    description: USD price computed from the official standard API pricing table for the detected model. This is a pricing reference, not ChatGPT/Codex billing.')
        if costs.get('price_usd_breakdown_api_standard'):
            ub = costs['price_usd_breakdown_api_standard']
            print('  price_usd_breakdown_api_standard:')
            print(f"    input_component: {fmt_num(ub.get('input_component'))}")
            print('      description: USD cost contribution from input_tokens at the standard API input price.')
            print(f"    cached_input_component: {fmt_num(ub.get('cached_input_component'))}")
            print('      description: USD cost contribution from cached_input_tokens at the lower cached-input API price.')
            print(f"    output_component: {fmt_num(ub.get('output_component'))}")
            print('      description: USD cost contribution from output_tokens at the standard API output price.')
        print(f"  model_for_pricing: {costs.get('model_for_pricing')}")
        if costs.get('pricing_notes'):
            print('  pricing_notes:')
            for note in costs['pricing_notes']:
                print(f'    - {note}')

    print('\nsource_fidelity')
    print('---------------')
    print(f"origin: {fidelity['origin']}")
    print(f"event_type: {fidelity['event_type']}")
    print(f"event_payload_type: {fidelity['event_payload_type']}")
    print(f"why_faithful: {fidelity['why_faithful']}")
    print(f"limitation: {fidelity['limitation']}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Report Codex token usage from the latest session JSONL.')
    parser.add_argument('--session-file', help='Explicit path to a Codex session JSONL file.')
    parser.add_argument('--sessions-dir', default=str(CODEX_SESSIONS_DIR), help='Base directory for Codex session JSONL files.')
    parser.add_argument('--json', action='store_true', help='Emit JSON instead of human-readable text.')
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    session_file = Path(args.session_file) if args.session_file else latest_session_file(Path(args.sessions_dir).expanduser())
    data = load_session(session_file)
    report = build_report(data)
    if args.json:
        json.dump(report, sys.stdout, ensure_ascii=False, indent=2)
        sys.stdout.write('\n')
    else:
        print_human(report)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
